# remove 'version:' to silence the warning

services:
  data:
    container_name: db
    build:
      context: ./app/data
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks: [myapp]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  data-script:
    container_name: data-script
    build:
      context: ./app/data-script
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      data:
        condition: service_healthy
    networks: [myapp]

  back:
    container_name: api
    build:
      context: ./app/back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      data:
        condition: service_healthy
    networks:
      myapp:
        aliases: [api]  # lets front call http://api:3000

  front:
    container_name: front
    build:
      context: ./app/front
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on: [back]
    networks: [myapp]

networks:
  myapp: {}